// Biblioteca de actividades que se van desbloqueando mes con mes.
// Cada actividad trae `unlock`: el mes de uso (0 = el primer mes) en que aparece como «Nueva».
// Las 12 actividades originales (en data.js) siempre están disponibles.
// Más adelante estas listas pueden ampliarse con la app o generarse con IA (fase 3).

export const MORE_MATS = {
  globos: 'Globos', arroz: 'Arroz crudo', botellas: 'Botellas de plástico', periodico: 'Periódico', bolsas: 'Bolsas de papel',
  pelota: 'Pelota', toalla: 'Toalla', gis: 'Gis o tiza', jabon: 'Jabón', fruta: 'Fruta', frijol: 'Frijoles secos', libros: 'Libros',
};

export const MORE_ACTS = [
  // ---- Mes 0 ----
  { id: 13, unlock: 0, t: 'Globo al aire', mats: ['globos'], age: [2, 8], min: 15, sk: 'motricidad', energy: 'Movida', why: 'Coordinación ojo-mano y atención.', steps: ['El adulto infla un globo y lo anuda.', 'Traten de que no toque el piso, golpeándolo con la mano.', 'Suban el reto: solo con los codos, con la cabeza o con los pies.', 'Cuenten cuántos golpes seguidos logran. Al terminar, recoge los globos; los restos de uno reventado son peligrosos si se los llevan a la boca.'] },
  { id: 14, unlock: 0, t: 'Caja de arroz', mats: ['arroz', 'cucharas', 'vasos'], age: [3, 6], min: 20, sk: 'calma', energy: 'Tranquila', why: 'Exploración con el tacto y control fino de las manos.', steps: ['Pon arroz crudo en una charola o caja grande, sobre una toalla.', 'Dale cucharas y vasos para llenar, vaciar y pasar de uno a otro.', 'Escondan una tapa o una cuchara y pídele que la encuentre con las manos.', 'Barran juntos al final. Acompáñalo siempre: el arroz no se come y los niños más pequeños pueden llevárselo a la boca.'] },
  { id: 15, unlock: 0, t: 'Baile congelado', mats: [], age: [2, 8], min: 10, sk: 'motricidad', energy: 'Movida', why: 'Autocontrol, escucha y expresión con el cuerpo.', steps: ['Pongan su canción favorita (sin pantalla, solo el audio).', 'Bailen libremente mientras suena.', 'Cuando pares la música, todos se quedan como estatuas.', 'Cambien de turno: tu hijo controla la música y tú bailas.'] },
  { id: 16, unlock: 0, t: 'Lavado de juguetes', mats: ['agua', 'jabon', 'toalla'], age: [2, 6], min: 20, sk: 'calma', energy: 'Tranquila', why: 'Clasificar, concentración y cuidado de sus cosas.', steps: ['Pon una tina o un bote con poca agua y un poco de jabón, sobre una toalla.', 'Elige juguetes que se puedan mojar.', 'Que los talle, los enjuague y los ponga a secar sobre la toalla.', 'Cuenten cuántos lavaron. Nunca lo dejes solo cerca del agua.'] },
  // ---- Mes 1 ----
  { id: 17, unlock: 1, t: 'Carrera de obstáculos', mats: ['almohadas', 'cinta'], age: [3, 9], min: 20, sk: 'motricidad', energy: 'Movida', why: 'Planeación del movimiento y equilibrio.', steps: ['Arma un camino: almohadas para saltar, una línea de cinta para caminar y una silla para pasar por debajo.', 'Recórranlo juntos la primera vez, despacio.', 'Pídele que invente un obstáculo nuevo.', 'Midan el tiempo con un conteo en voz alta y traten de mejorarlo.'] },
  { id: 18, unlock: 1, t: 'Dibujo en sal', mats: ['sal', 'caja'], age: [3, 7], min: 15, sk: 'motricidad', energy: 'Tranquila', why: 'Preparación para escribir: trazos con el dedo.', steps: ['Cubre con sal el fondo de una tapa de caja o una charola.', 'Con un dedo, dibuja líneas, círculos y zigzags.', 'Pídele que copie tu dibujo o que escriba la primera letra de su nombre.', 'Agita la charola para borrar y empezar de nuevo.'] },
  { id: 19, unlock: 1, t: 'Bolsa misteriosa', mats: ['bolsas', 'cucharas'], age: [3, 8], min: 15, sk: 'lenguaje', energy: 'Tranquila', why: 'Vocabulario y descripción de lo que se siente.', steps: ['Mete un objeto en una bolsa de papel sin que lo vea.', 'Que meta la mano, sin mirar, y lo describa: «es duro», «es liso».', 'Adivina qué es. Después cambien de papel.', 'Para subir el reto, usa objetos más parecidos entre sí.'] },
  { id: 20, unlock: 1, t: 'Teléfono de vasos', mats: ['vasos', 'cuerda'], age: [4, 9], min: 15, sk: 'lenguaje', energy: 'Tranquila', why: 'Escucha atenta y hablar con claridad.', steps: ['Haz un hoyito en el fondo de dos vasos de cartón o plástico y pasa un cordón por cada uno, con un nudo por dentro.', 'Cada quien toma un vaso y se separan hasta que el cordón quede tenso.', 'Uno habla en voz baja y el otro escucha por el vaso.', 'Manden mensajes secretos de 3 palabras y cuenten cuántos entendieron.'] },
  // ---- Mes 2 ----
  { id: 21, unlock: 2, t: 'Torre de cajas', mats: ['caja'], age: [2, 6], min: 15, sk: 'logica', energy: 'Tranquila', why: 'Tamaños, equilibrio y paciencia.', steps: ['Junta cajas de distintos tamaños (cereal, galletas, zapatos).', 'Ordénalas juntos de la más grande a la más chica.', 'Construyan la torre más alta que se sostenga.', 'Derríbenla con una pelota o con un «¡pum!» y vuelvan a empezar.'] },
  { id: 22, unlock: 2, t: 'Mi sombra con gis', mats: ['gis'], age: [4, 10], min: 20, sk: 'creatividad', energy: 'Movida', why: 'Observación y relación entre luz, cuerpo y espacio.', steps: ['Salgan al patio un día soleado.', 'Que se pare quieto mientras tú marcas el contorno de su sombra con gis.', 'Regresen un par de horas después y marquen de nuevo: ¿se movió?', 'Dibujen la cara y la ropa dentro de cada sombra.'] },
  { id: 23, unlock: 2, t: 'Ensalada de frutas', mats: ['fruta', 'cucharas', 'vasos'], age: [3, 9], min: 25, sk: 'motricidad', energy: 'Tranquila', why: 'Autonomía en la cocina y probar sabores nuevos.', steps: ['Lavan juntos 3 o 4 frutas distintas.', 'El adulto corta; tu hijo pasa la fruta a un tazón con las manos o con una cuchara. En niños menores de 4 años, corta la fruta redonda (como uvas) en cuartos a lo largo.', 'Mezclan con cuidado y sirven en vasos.', 'Prueben cada fruta y elijan su favorita.'] },
  { id: 24, unlock: 2, t: 'Respira como globo', mats: [], age: [3, 9], min: 5, sk: 'calma', energy: 'Tranquila', why: 'Aprender a calmarse con la respiración.', steps: ['Siéntense cómodos y pónganse las manos en la panza.', 'Inhalen por la nariz: la panza se infla como un globo.', 'Exhalen despacio por la boca: el globo se desinfla.', 'Repitan 5 veces. Úsenlo después cuando haya un berrinche o antes de dormir.'] },
  // ---- Mes 3 ----
  { id: 25, unlock: 3, t: 'Simón dice', mats: [], age: [3, 9], min: 10, sk: 'lenguaje', energy: 'Movida', why: 'Seguir instrucciones y atención.', steps: ['Explica la regla: solo se obedece si dices «Simón dice».', 'Da órdenes sencillas: tocarse la nariz, saltar, dar una vuelta.', 'Si alguien se equivoca, no pasa nada: se ríen y siguen.', 'Cambien de turno para que tu hijo dé las órdenes.'] },
  { id: 26, unlock: 3, t: 'Clasificar frijoles', mats: ['frijol', 'vasos'], age: [4, 8], min: 15, sk: 'logica', energy: 'Tranquila', why: 'Contar, agrupar y comparar cantidades.', steps: ['Mezcla dos tipos de frijoles secos (por ejemplo, negros y pintos) en un plato.', 'Que los separe en dos vasos.', 'Cuenten cuántos hay de cada uno y cuál tiene más.', 'Solo para niños mayores de 3 años y siempre con un adulto: los frijoles secos no se comen y son pequeños.'] },
  { id: 27, unlock: 3, t: 'Boliche de botellas', mats: ['botellas', 'pelota'], age: [3, 9], min: 15, sk: 'motricidad', energy: 'Movida', why: 'Puntería, fuerza y conteo.', steps: ['Pon 6 botellas de plástico vacías en triángulo.', 'Marquen con cinta o un zapato la línea de lanzamiento.', 'Rueden la pelota y cuenten cuántas botellas tiran.', 'Sumen sus puntos en 3 tiros y tracen una meta nueva.'] },
  { id: 28, unlock: 3, t: 'Cuento con sombras de manos', mats: ['linterna'], age: [4, 10], min: 20, sk: 'lenguaje', energy: 'Tranquila', why: 'Imaginación y narración con inicio, problema y final.', steps: ['Apaguen la luz y apunten la linterna a la pared.', 'Hagan figuras con las manos: conejo, pájaro, perro.', 'Inventen una historia con inicio, problema y final.', 'Dejen que tu hijo ponga la voz a cada personaje.'] },
  // ---- Mes 4 ----
  { id: 29, unlock: 4, t: 'Tren de cajas', mats: ['caja', 'cuerda'], age: [2, 6], min: 20, sk: 'creatividad', energy: 'Movida', why: 'Juego simbólico y coordinación.', steps: ['Junta 3 o 4 cajas y únelas con cordón para hacer un tren.', 'Decoren cada vagón con crayones o papel.', 'Jálenlo por la casa y hagan estaciones.', 'Pregunta quién viaja y a dónde va.'] },
  { id: 30, unlock: 4, t: 'Memoria con tapas', mats: ['tapas', 'vasos'], age: [3, 7], min: 15, sk: 'logica', energy: 'Tranquila', why: 'Memoria visual y atención.', steps: ['Pon 3 tapas de colores distintos sobre la mesa.', 'Que las mire 10 segundos y cierre los ojos.', 'Quita una tapa. Al abrir los ojos, adivina cuál falta.', 'Aumenta a 5 o 6 tapas. Usa solo tapas grandes si hay niños menores de 3 años cerca.'] },
  { id: 31, unlock: 4, t: 'Mercadito', mats: ['caja', 'papel', 'crayones'], age: [4, 9], min: 30, sk: 'logica', energy: 'Tranquila', why: 'Contar, sumar y turnos para hablar.', steps: ['Arma una tienda con productos de la alacena y letreros con precios en papel.', 'Hagan «dinero» de papel con crayones.', 'Uno vende y otro compra. Practiquen sumar y dar cambio.', 'Cambien de papel y comparen precios.'] },
  { id: 32, unlock: 4, t: 'Estatuas con música', mats: [], age: [2, 7], min: 10, sk: 'calma', energy: 'Movida', why: 'Pasar de la energía a la calma.', steps: ['Pongan música alegre y bailen.', 'Cuando baje la música, se quedan quietos como estatuas.', 'Poco a poco usa música más lenta hasta que se queden en calma.', 'Cierra con 3 respiraciones profundas.'] },
  // ---- Mes 5 ----
  { id: 33, unlock: 5, t: 'Burbujas caseras', mats: ['jabon', 'agua', 'pasta'], age: [3, 9], min: 20, sk: 'creatividad', energy: 'Movida', why: 'Observación y soplar con control.', steps: ['Mezcla en un recipiente agua con un poco de jabón líquido.', 'Usa un macarrón o penne como varita: sopla por un extremo y moja el otro.', 'Hagan burbujas afuera y cuenten cuántas logran.', 'Se limpia con un trapo. Cuida que no se tomen la mezcla.'] },
  { id: 34, unlock: 5, t: 'Collage de periódico', mats: ['periodico', 'tijeras', 'papel'], age: [5, 10], min: 30, sk: 'creatividad', energy: 'Tranquila', why: 'Creatividad y motricidad fina.', steps: ['Busca letras, colores y fotografías en un periódico viejo.', 'Recorta (con apoyo del adulto si es necesario) lo que le llame la atención.', 'Pega y acomoda en una hoja para formar un animal o una cara.', 'Ponle título a su obra y exhíbela.'] },
  { id: 35, unlock: 5, t: 'Torre de vasos a ciegas', mats: ['vasos'], age: [4, 9], min: 15, sk: 'logica', energy: 'Tranquila', why: 'Comunicación y paciencia en equipo.', steps: ['Pongan 6 vasos sobre la mesa.', 'Uno se tapa los ojos o se voltea.', 'El otro le da instrucciones para armar una torre: «un vaso a la izquierda…».', 'Cambien de papel y comparen sus torres.'] },
  { id: 36, unlock: 5, t: 'Carrera de cuchara y pelota', mats: ['cucharas', 'pelota'], age: [4, 10], min: 15, sk: 'motricidad', energy: 'Movida', why: 'Equilibrio y concentración al moverse.', steps: ['Marca con cinta o gis una salida y una meta.', 'Cada quien lleva una pelota pequeña sobre una cuchara sin que se caiga.', 'Si se cae, regresa a la salida.', 'Suban el reto: caminar de lado, rodear una silla o hacerlo en un pie.'] },
  // ---- Mes 6 ----
  { id: 37, unlock: 6, t: 'Rompecabezas casero', mats: ['papel', 'crayones', 'tijeras'], age: [4, 9], min: 25, sk: 'logica', energy: 'Tranquila', why: 'Percepción de formas y resolución de problemas.', steps: ['Que dibuje una escena en una hoja entera.', 'El adulto la corta en 4 a 8 piezas con tijeras.', 'Mézclenlas y ármenlo de nuevo.', 'Intercambien con alguien más de la familia para armarlo.'] },
  { id: 38, unlock: 6, t: 'Yoga de animales', mats: ['cobija'], age: [3, 8], min: 15, sk: 'calma', energy: 'Tranquila', why: 'Flexibilidad, equilibrio y respiración.', steps: ['Extiende una cobija en el piso.', 'Imiten animales: gato (en cuatro apoyos), cobra (boca abajo, subiendo el pecho), árbol (parados en un pie).', 'Mantengan cada postura contando hasta 5, sin forzar.', 'Termina acostados, respirando despacio.'] },
  { id: 39, unlock: 6, t: 'Cocinita con ollas', mats: ['ollas', 'cucharas', 'agua'], age: [2, 6], min: 20, sk: 'creatividad', energy: 'Tranquila', why: 'Juego simbólico y vocabulario.', steps: ['Pon ollas, cucharas y un poco de agua en una zona que se pueda mojar.', 'Que prepare una «sopa» y te sirva.', 'Pregunta: ¿qué lleva? ¿está caliente? ¿para quién es?', 'Limpien juntos al terminar.'] },
  { id: 40, unlock: 6, t: 'Atrapa la sorpresa', mats: ['calcetines', 'bolsas'], age: [2, 7], min: 10, sk: 'motricidad', energy: 'Movida', why: 'Lanzar, atrapar y puntería.', steps: ['Haz una pelota enrollando calcetines.', 'Pon una bolsa de papel abierta a 2 pasos de distancia.', 'Lancen la pelota para meterla; cada acierto es un punto.', 'Alejen la bolsa un paso cada vez que lleguen a 5 puntos.'] },
  // ---- Mes 7 ----
  { id: 41, unlock: 7, t: 'Lectura con linterna', mats: ['linterna', 'cobija', 'libros'], age: [3, 10], min: 20, sk: 'calma', energy: 'Tranquila', why: 'Gusto por la lectura y rutina para dormir.', steps: ['Hagan una cueva con una cobija sobre sillas o el sillón.', 'Entren con una linterna y libros.', 'Lee un cuento en voz baja e ilumina cada página.', 'Pídele que invente un final diferente.'] },
  { id: 42, unlock: 7, t: 'Encuentra la letra', mats: ['papel', 'crayones'], age: [4, 7], min: 15, sk: 'lenguaje', energy: 'Tranquila', why: 'Reconocer letras y sonidos.', steps: ['Escribe en una hoja la primera letra de su nombre.', 'Búsquenla en etiquetas, cajas y libros de la casa.', 'Cada vez que la encuentre, la marca con un círculo.', 'Cierren diciendo palabras que empiecen con esa letra.'] },
  { id: 43, unlock: 7, t: 'Puntería al blanco', mats: ['pelota', 'caja'], age: [3, 9], min: 15, sk: 'motricidad', energy: 'Movida', why: 'Puntería y cálculo de distancia.', steps: ['Pon una caja grande en el piso, de lado.', 'Marquen la línea de lanzamiento con cinta o con un zapato.', 'Lancen la pelota para meterla; cada acierto vale un punto.', 'Alejen la caja y comparen sus resultados.'] },
  { id: 44, unlock: 7, t: 'Sonajas con botellas', mats: ['botellas', 'arroz', 'cinta'], age: [3, 8], min: 25, sk: 'creatividad', energy: 'Movida', why: 'Ritmo, causa y efecto.', steps: ['El adulto pone un poco de arroz dentro de una botella pequeña y cierra bien la tapa.', 'Asegura la tapa con cinta para que no se abra.', 'Decoren con cinta de colores y agítenla al ritmo de una canción.', 'Hagan varias con distintas cantidades de arroz y comparen el sonido.'] },
];
